apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    app.kubernetes.io/name: kube-controller-manager
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    pyrra.dev/component: kube-controller-manager
    role: alert-rules
  name: kube-controller-manager-request-errors
  namespace: monitoring
spec:
  description: "The Kubernetes controller manager is a daemon that embeds the core control loops shipped with Kubernetes. \nIn applications of robotics and automation, a control loop is a non-terminating loop that regulates the state of the system. \nIn Kubernetes, a controller is a control loop that watches the shared state of the cluster through the apiserver and makes changes attempting to move the current state towards the desired state. Examples of controllers that ship with Kubernetes today are the replication controller, endpoints controller, namespace controller, and serviceaccounts controller.\n"
  indicator:
    ratio:
      errors:
        metric: rest_client_requests_total{job="kube-controller-manager",code=~"5..|<error>"}
      total:
        metric: rest_client_requests_total{job="kube-controller-manager"}
  target: "99"
  window: 2w
