apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics-api
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.7.2
  name: metrics-server
  namespace: monitoring
spec:
  ports:
  - name: https
    port: 443
    targetPort: 4443
  selector:
    app.kubernetes.io/component: metrics-api
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: kube-prometheus
