apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/component: metrics-api
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.7.2
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: metrics-server
    namespace: monitoring
  version: v1beta1
  versionPriority: 100
