apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.83.0
    prometheus: k8s
    pyrra.dev/component: prometheus-operator
    role: alert-rules
  name: prometheus-operator-http-errors
  namespace: monitoring
spec:
  description: "The Prometheus Operator makes HTTP requests to the Kubernetes API server to read and write the objects.\nIf this firing the Prometheus Operator might not be able read and write the latest objects. \n"
  indicator:
    ratio:
      errors:
        metric: prometheus_operator_kubernetes_client_http_requests_total{job="prometheus-operator",namespace="monitoring",status_code=~"5.."}
      total:
        metric: prometheus_operator_kubernetes_client_http_requests_total{job="prometheus-operator",namespace="monitoring"}
  target: "99.5"
  window: 2w
