apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-rule-evaluation-failures
  namespace: monitoring
spec:
  description: Rule and alerting rules are being evaluated every few seconds. This needs to work for recording rules to be created and most importantly for alerts to be evaluated.
  indicator:
    ratio:
      errors:
        metric: prometheus_rule_evaluation_failures_total{job="prometheus-k8s"}
      total:
        metric: prometheus_rule_evaluations_total{job="prometheus-k8s"}
  target: "99.99"
  window: 2w
