apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kubernetes
    app.kubernetes.io/name: pyrra
    app.kubernetes.io/version: 0.8.4
  name: pyrra-kubernetes
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pyrra-kubernetes
subjects:
- kind: ServiceAccount
  name: pyrra-kubernetes
  namespace: monitoring
